# Generated by Django 5.1.3 on 2024-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
